### ISSUE TITLE
Add -hide flag as a command line option

### ISSUE THREAD

**Issue by STH-Dev** [STH-Dev/linux-bench#52]
The new Linux-Bench web application has a comparison tool. We also added the ability to hide results from public view. Need to add a flag so any pre-production hardware that gets benchmarked can be hidden before public release.

**Comment by chuckleb** [comment]
#55 replaces this one

**Comment by STH-Dev** [comment]
Assigning to PatriotEagle07 - as discussed, this can be simply -h

**Comment by STH-Dev** [comment]
Ok the new parser is looking for text: Private Result

If we can have a -p flag and then print the text Private Result on a line when that flag is present, the parser will then hide the result.

**Comment by PatriotEagle07** [comment]
-p Private Results flag added   Simply Echos "Private Result"  to the log, web parser will not publish anything flagged Private.
