### ISSUE TITLE
Add flag for e-mail address

### ISSUE THREAD

**Issue by STH-Dev** [STH-Dev/linux-bench#55]
Capture e-mail address via command line -email flag

Suggestion from Ian @ Anandtech - after the benchmark ends, send an e-mail with the result link so that one knows that the benchmark completed and has easy access to the result.

**Comment by chuckleb** [comment]
Sending email out may be hard depending on how mail servers, relaying allowed, etc

**Comment by STH-Dev** [comment]
The sending part I think we will have covered. Just need the flag. Been talking to @PatriotEagle07 about this over gchat this morning.

**Comment by PatriotEagle07** [comment]
How is the sending part covered?   ... but yes input flags are easy with bash...

**Comment by STH-Dev** [comment]
Was thinking we can send from the server side.

**Comment by STH-Dev** [comment]
OK so the e-mail bit - we have the http://beta.linux-bench.com/ is now sending me e-mails whenever someone uploads a result (using the github version curl http://linux-bench.com/lb-test.sh | bash

I think we can update if we need to.

**Comment by PatriotEagle07** [comment]
-e email@email.net will shove email@email.net into the log for the webparser to handle sending the emails.
